# plot_size <- c("", "400px", "800px")
ui <- fluidPage(
	br(),
	titlePanel("Environmental Effect on Fibre Glass Composites, Exposed Samples, Normalized Data"),
	fluidRow(
		br(), br(),
		column(3,
					 br(), br(),br(),br(), br(),br(), br(), br(),
					 wellPanel(
					 	checkboxGroupInput("AnalCrit", "Analysis Criteria:",
					 										 choices = c("Material", "Coating", "Cure"),
					 										 selected ="Material")
					 )
		),
		column(9,
					 tabsetPanel(
					 	tabPanel("Roughness Scatter Plots",
					 					 br(),
					 					 h2("Exposed Samples, Roughness Scatter Plots"),
					 					 br(),
					 					 selectInput("PlotSizeTab1", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("rough_jitter1_UIO"),
					 					 br(),br(),
					 					 uiOutput("rough_jitter2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Roughness Box Plots", 
					 					 br(),
					 					 h2("Exposed Samples, Roughness Box Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab2", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("rough_box1_UIO"), br(), br(),
					 					 uiOutput("rough_box2_UIO"), br(), br()
					 	),
					 	tabPanel("Roughness Trends",
					 					 br(),
					 					 h2("Exposed Samples, Roughness General Trends:"),
					 					 br(),
					 					 selectInput("PlotSizeTab3", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("rough_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("rough_line2_UIO"),
					 					 br(),
					 					 h2("Exposed Samples, Gained Roughness:"),
					 					 br(),
					 					 selectInput("Plot2SizeTab3", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("rough2_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("rough2_line2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Roughness Model",
					 					 br(),
					 					 h2("Exposed Samples, Roughness Model Trends:"),
					 					 br(),
					 					 selectInput("PlotSizeTabG", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("rough_smooth1_UIO"),
					 					 br(), br(),
					 					 uiOutput("rough_smooth2_UIO"),
					 					 br(), br()
					 					 # h2("Exposed Samples, Roughness Gained:"),
					 					 # br(),
					 					 # selectInput("Plot2SizeTabG", "Heghit of Plots in Pixels:",
					 					 # 						choices = seq(100, 1000, 50), selected = 400),
					 					 # hr(),
					 					 # uiOutput("rough2_smooth1_UIO"),
					 					 # br(), br(),
					 					 # uiOutput("rough2_smooth2_UIO"),
					 					 # br(), br()
					 	),
					 	tabPanel("Hardness Scatter Plots:",
					 					 br(),
					 					 h2("Exposed Samples, Hardness, Scatter Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab4", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("hard_jitter1_UIO"),
					 					 br(),br(),
					 					 uiOutput("hard_jitter2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Hardness Box Plots:",
					 					 br(),
					 					 h2("Exposed Samples, Hardness, Box Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab5", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("hard_box1_UIO"),
					 					 br(),br(),
					 					 uiOutput("hard_box2_UIO"),
					 					 br(),br()
					 	),
					 	tabPanel("Hardness Average Trends",
					 					 br(),
					 					 h2("Exposed Samples, Hardness Average Trends:"),
					 					 br(),
					 					 selectInput("PlotSizeTab6", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("hard_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("hard_line2_UIO"),
					 					 br(),
					 					 h2("Exposed Samples, Gained Hardness:"),
					 					 br(),
					 					 selectInput("Plot2SizeTab5", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("hard2_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("hard2_line2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Flexural Strength Scatter Plots",
					 					 br(),
					 					 h2("Exposed Samples, Flexural Stress Scatter Plots"),
					 					 br(),
					 					 selectInput("PlotSizeTab7", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("flexural_jitter1_UIO"),
					 					 br(),br(),
					 					 uiOutput("flexural_jitter2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Flexural Strength Box Plots", 
					 					 br(),
					 					 h2("Exposed Samples, Flexural Strength Box Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab8", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("flexural_box1_UIO"), 
					 					 br(), br(),
					 					 uiOutput("flexural_box2_UIO"), 
					 					 br(), br()
					 	),
					 	tabPanel("Flexural Strength Average Trends",
					 					 br(),
					 					 h2("Exposed Samples, Flexural Strength, Average Trends:"),
					 					 br(),
					 					 selectInput("PlotSizeTab9", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("flexural_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("flexural_line2_UIO"),
					 					 br(), br()
					 	)
					 )
		)
	)
)
