# plot_size <- c("", "400px", "800px")
ui <- fluidPage(
	br(),
	titlePanel("Environmental Effect on Fibre Glass Composites, Exposed Samples"),
	fluidRow(
		br(), br(),
		column(3,
					 br(), br(),br(),br(), br(),br(), br(), br(),
					 wellPanel(
					 	checkboxGroupInput("AnalCrit", "Analysis Criteria:",
					 										 choices = c("Material", "Coating", "Cure"),
					 										 selected ="Material")
					 	)
					 ),
		column(9,
					 tabsetPanel(
					 	tabPanel("Roughness Scatter Plots",
					 					 br(),
					 					 h2("Exposed Samples, Roughness Scatter Plots"),
					 					 br(),
					 					 selectInput("PlotSizeTab1", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("rough_jitter1_UIO"),
					 					 br(),br(),
					 					 uiOutput("rough_jitter2_UIO"),
					 					 br(), hr()
					 	),
					 	# tabPanel("Roughness, Time Varying ScatterPlots",
					 	# 				 br(),
					 	# 				 h2("Exposed Samples, Roughness, Time Varying Scatter Plots"),
					 	# 				 br(),
					 	# 				 uiOutput ("rough_JT1_UIO"),
					 	# 				 br(),
					 	# 				 uiOutput ("rough_JT2_UIO"),
					 	# 				 hr(),
					 	# 				 fluidRow(
					 	# 				 	column(4, selectInput("Plot2SizeTab1", "Heghit of The Graph in Pixels:",
					 	# 				 												choices = seq(100, 1000, 50), selected = 250)),
					 	# 				 	column(2),
					 	# 				 	column(5, sliderInput("TimeRJ", label="Time in Days (0, 30, 90, 180, 270, 360):
					 	# 				 												0 = Day 0, 
					 	# 				 												1 = Day 30,
					 	# 				 												2 = Day 90,
					 	# 				 												3 = Day 180,
					 	# 				 												4 = Day 270,
					 	# 				 												5 = Day 360",
					 	# 				 												min = 0, max = 5, step = 1, value = 0)))
					 	# 				 ),
					 	tabPanel("Roughness Box Plots", 
					 					 br(),
					 					 h2("Exposed Samples, Roughness Box Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab2", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("rough_box1_UIO"), br(), br(),
					 					 uiOutput("rough_box2_UIO"), br(), br()
					 	),
					 	# tabPanel("Roughness, Time Varying Box Plots",
					 	# 				 br(),
					 	# 				 h2("Exposed Samples, Roughness, Time Varying Box Plots"),
					 	# 				 br(),
					 	# 				 uiOutput ("rough_BT1_UIO"),
					 	# 				 br(),
					 	# 				 uiOutput ("rough_BT2_UIO"),
					 	# 				 hr(),
					 	# 				 fluidRow(
					 	# 				 	column(4, selectInput("Plot2SizeTab2", "Heghit of The Graph in Pixels:",
					 	# 				 												choices = seq(100, 1000, 50), selected = 250)),
					 	# 				 	column(2),
					 	# 				 	column(5, sliderInput("TimeRB", label="Time in Days (0, 30, 90, 180, 270, 360):
					 	# 				 												0 = Day 0, 
					 	# 				 												1 = Day 30,
					 	# 				 												2 = Day 90,
					 	# 				 												3 = Day 180,
					 	# 				 												4 = Day 270,
					 	# 				 												5 = Day 360",
					 	# 				 												min = 0, max = 5, step = 1, value = 0))
					 	# 				 	
					 	# 				 )
					 	# ),
					 	tabPanel("Roughness Average Trends",
					 					 br(),
					 					 h2("Exposed Samples, Roughness Average Trends:"),
					 					 br(),
					 					 selectInput("PlotSizeTab3", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("rough_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("rough_line2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Hardness Scatter Plots:",
					 					 br(),
					 					 h2("Exposed Samples, Hardness, Scatter Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab4", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("hard_jitter1_UIO"),
					 					 br(),br(),
					 					 uiOutput("hard_jitter2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Hardness Box Plots:",
					 					 br(),
					 					 h2("Exposed Samples, Hardness, Box Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab5", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("hard_box1_UIO"),
					 					 br(),br(),
					 					 uiOutput("hard_box2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Hardness Average Trends",
					 					 br(),
					 					 h2("Exposed Samples, Hardness Average Trends:"),
					 					 br(),
					 					 selectInput("PlotSizeTab6", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("hard_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("hard_line2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Flexural Strength Scatter Plots",
					 					 br(),
					 					 h2("Exposed Samples, Flexural Stress Scatter Plots"),
					 					 br(),
					 					 selectInput("PlotSizeTab7", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput ("flexural_jitter1_UIO"),
					 					 br(),br(),
					 					 uiOutput("flexural_jitter2_UIO"),
					 					 br(), br()
					 	),
					 	tabPanel("Flexural Strength Box Plots", 
					 					 br(),
					 					 h2("Exposed Samples, Flexural Strength Box Plots:"),
					 					 br(),
					 					 selectInput("PlotSizeTab8", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("flexural_box1_UIO"), 
					 					 br(), br(),
					 					 uiOutput("flexural_box2_UIO"), 
					 					 br(), br()
					 	),
					 	tabPanel("Flexural Strength Average Trends",
					 					 br(),
					 					 h2("Exposed Samples, Flexural Strength, Average Trends:"),
					 					 br(),
					 					 selectInput("PlotSizeTab9", "Heghit of Plots in Pixels:",
					 					 						choices = seq(100, 1000, 50), selected = 400),
					 					 hr(),
					 					 uiOutput("flexural_line1_UIO"),
					 					 br(), br(),
					 					 uiOutput("flexural_line2_UIO"),
					 					 br(), br()
					 	)
					 )
					 )
		)
	)
